// Generated by web_app/scripts/generate_debug_js.sh
// Enables verbose debug logging for the demo. Do NOT commit this file.
window.__ESS_DEBUG__ = true;
console.log('ESS demo debug mode enabled (window.__ESS_DEBUG__ = true)');
