#!/usr/bin/env bash
# Generate a small debug JS file that enables the demo's debug logging.
# Usage: ./generate_debug_js.sh
set -euo pipefail
OUT_DIR="$(dirname "$0")/.."/web
mkdir -p "$OUT_DIR"
cat > "$OUT_DIR/debug.js" <<'JS'
// Generated by example/flutter_web_demo/scripts/generate_debug_js.sh
// Enables verbose debug logging for the demo. Do NOT commit this file.
window.__ESS_DEBUG__ = true;
console.log('ESS demo debug mode enabled (window.__ESS_DEBUG__ = true)');
JS

echo "Wrote $OUT_DIR/debug.js. Open the demo page and check DevTools console for logs."
